name: Building Flutter App

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build_web:
    name: Run Flutter Build (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: "Flutter version log"
        run: flutter --version
        
      - name: "Dependencies installation"
        run: flutter pub get
        working-directory: ./web

      - name: "Cleaning build"
        run: flutter clean
        working-directory: ./web

      - name: "Building web app"
        run: |
          flutter build web --release
        working-directory: ./web

